/* ------------------------------------------------------------------ */
/*  Trust & Authenticity — the shared vocabulary.                      */
/*                                                                     */
/*  Principle: show users what has actually been VERIFIED, never tell  */
/*  them who to trust. UpNova doesn't guarantee skill or originality — */
/*  it labels the evidence it actually has:                            */
/*                                                                     */
/*   Account signals (earned, NEVER purchasable — Pro/Business         */
/*   subscriptions grant zero of these):                               */
/*     identity_verified  — UpNova verified the person's identity      */
/*     business_verified  — UpNova verified the organization           */
/*     student_verified   — UpNova verified student status             */
/*                                                                     */
/*   Content signals (per post, computed/recorded server-side):        */
/*     verified_work      — the work is associated with a COMPLETED    */
/*                          UpNova project or booking (server-checked) */
/*     client_confirmed   — the counterparty confirmed it happened     */
/*     creator_attested   — the creator confirms the right to publish  */
/*                          and isn't presenting someone else's work   */
/*                          as their own (a claim, labeled as one)     */
/*                                                                     */
/*   Disclosure (replaces a bare "Original Work" declaration):         */
/*     original · ai_assisted · ai_generated · credited · unspecified  */
/*                                                                     */
/*  This file is a REGISTRY — new signal types are new entries, not    */
/*  new systems. Rendering reads the registry; nothing is hard-coded   */
/*  per category.                                                      */
/* ------------------------------------------------------------------ */

export type DisclosureType = "original" | "ai_assisted" | "ai_generated" | "credited" | "unspecified";

export const DISCLOSURES: Record<DisclosureType, { label: string; chip: string | null; hint: string }> = {
  original: {
    label: "Original work",
    chip: null, // originality is claimed via attestation, not self-labeled as proof
    hint: "You made this yourself, without AI generation.",
  },
  ai_assisted: {
    label: "AI-assisted",
    chip: "AI-Assisted",
    hint: "You made this with AI tools helping (editing, cleanup, iteration).",
  },
  ai_generated: {
    label: "AI-generated",
    chip: "AI-Generated",
    hint: "This was generated by AI from your direction.",
  },
  credited: {
    label: "Credited work",
    chip: "Credited Work",
    hint: "Someone else made or co-made this — credit them by name.",
  },
  unspecified: {
    label: "Not specified",
    chip: null,
    hint: "No disclosure attached.",
  },
};

/* -------------------- account-level badges (registry) -------------------- */

export type AccountBadge = "identity_verified" | "business_verified" | "student_verified";

export const ACCOUNT_BADGES: Record<AccountBadge, { label: string; tone: string; description: string }> = {
  identity_verified: {
    label: "Identity Verified",
    tone: "lime",
    description: "UpNova has verified this person's identity. Only the badge is shown — never documents.",
  },
  business_verified: {
    label: "Business Verified",
    tone: "sky",
    description: "UpNova has verified this organization's business information.",
  },
  student_verified: {
    label: "Student Verified",
    tone: "violet",
    description: "UpNova has verified current student status at the listed campus.",
  },
};

/* --------------------- content-level chips (registry) --------------------- */

export type ContentSignal = "verified_work" | "client_confirmed" | "creator_attested";

export const CONTENT_SIGNALS: Record<ContentSignal, { label: string; tone: string; description: string }> = {
  verified_work: {
    label: "Verified Work",
    tone: "lime",
    description: "UpNova can associate this work with a completed UpNova project or booking.",
  },
  client_confirmed: {
    label: "Client Confirmed",
    tone: "violet",
    description: "The client on the linked transaction confirmed this work actually happened.",
  },
  creator_attested: {
    label: "Creator Attested",
    tone: "zinc",
    description:
      "The creator confirms they have the right to publish this and aren't presenting someone else's work as their own. This is the creator's claim — UpNova has not independently verified it.",
  },
};

/* ----------------------------- post trust shape ----------------------------- */

export interface PostTrust {
  /** set only when the server verified the link to a completed transaction */
  verifiedWork: { kind: "project" | "booking"; title: string; with: string } | null;
  clientConfirmed: boolean;
  attested: boolean;
  disclosure: DisclosureType;
  credit: string;
  /** true when the viewer is the linked counterparty and hasn't confirmed yet */
  canConfirm?: boolean;
}

/* ------------------------------ report reasons ------------------------------ */
/* Reports enter a moderation queue — they never auto-accuse or auto-ban. */

export const REPORT_REASONS = [
  { id: "stolen_work", label: "Someone is using my work" },
  { id: "impersonation", label: "Someone is impersonating me" },
  { id: "false_service_claim", label: "They claim work they didn't perform" },
  { id: "copyright", label: "Copyright / content concern" },
  { id: "other", label: "Something else" },
] as const;

export type ReportReason = (typeof REPORT_REASONS)[number]["id"];
